(() => {
  const ORGANIZATIONS = [
    { name: "Mastercard", icon: "Mastercard.png", credit: true },
    { name: "VISA", icon: "VISA.png", credit: true },
    { name: "AMEX", icon: "AMEX.png", credit: true },
    { name: "UnionPay", icon: "UnionPay.png", credit: true },
    { name: "JCB", icon: "JCB.png", credit: true },
    {
      name: "China T-Union",
      icon: "China_T-union.svg",
      credit: false,
    },
    {
      name: "RAILPLUS",
      icon: "RAILPLUS.jpg",
      credit: false,
    },
  ];

  const TIER_ORDER_MAP = {
    Mastercard: [
      "World Legend",
      "World Elite",
      "World Black",
      "World",
      "World Business",
      "Titanium",
      "Titanium Business",
      "Platinum",
      "Platinum Business",
      "Gold",
      "Gold Business",
      "Standard",
      "Standard Business",
    ],
    VISA: [
      "Infinite",
      "Infinite Business",
      "Signature",
      "Signature Business",
      "Platinum",
      "Platinum Business",
      "Gold",
      "Gold Business",
      "Classic",
      "Classic Business",
    ],
    AMEX: [
      "Centurion",
      "Centurion Business",
      "Icon",
      "Icon Business",
      "Platinum",
      "Platinum Business",
      "Max",
      "Max Business",
      "Gold",
      "Gold Business",
      "Select",
      "Select Business",
      "Green",
      "Green Business",
      "Member",
      "Member Business",
    ],
    UnionPay: [
      "Diamond",
      "Diamond Business",
      "Platinum",
      "Platinum Business",
      "Gold",
      "Gold Business",
      "Standard",
      "Standard Business",
    ],
    JCB: [
      "The Class",
      "The Class Business",
      "Platinum",
      "Platinum Business",
      "Gold",
      "Gold Business",
      "Standard",
      "Standard Business",
    ],
    "China T-Union": [],
  };

  const GLOBAL_TIER_ORDER = [
    ["World Legend"],
    ["World Elite"],
    ["World Black"],
    ["World"],
    ["World Business"],
    ["Infinite"],
    ["Infinite Business"],
    ["Signature"],
    ["Signature Business"],
    ["Centurion"],
    ["Centurion Business"],
    ["Icon"],
    ["Icon Business"],
    ["Diamond"],
    ["Diamond Business"],
    ["The Class"],
    ["The Class Business"],
    ["Titanium"],
    ["Titanium Business"],
    ["Platinum"],
    ["Platinum Business"],
    ["Max"],
    ["Max Business"],
    ["Gold"],
    ["Gold Business"],
    ["Select"],
    ["Select Business"],
    ["Classic"],
    ["Classic Business"],
    ["Standard"],
    ["Standard Business"],
    ["Green"],
    ["Green Business"],
    ["Member"],
    ["Member Business"],
  ];

  const TIER_ACCENT_CLASS = {
    "tier-accent-diamond": [
      "World Legend",
      "World Elite",
      "World Black",
      "Infinite",
      "Centurion",
      "Icon",
      "Diamond",
      "The Class",
    ],
    "tier-accent-spectrum": ["World", "Signature"],
    "tier-accent-platinum": ["Platinum", "Max"],
    "tier-accent-gold": ["Gold", "Select"],
  };

  window.cardConfig = Object.freeze({
    ORGANIZATIONS,
    TIER_ORDER_MAP,
    TIER_ACCENT_CLASS,
    GLOBAL_TIER_ORDER,
  });
})();
